name: Build and Deploy Kakula

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Set up Maven 3.9.9
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        mvn-version: '3.9.9'

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/*

    - name: Deploy to production (optional)
      run: mvn deploy # Se você tiver uma etapa de deploy





