name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Configuração do JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'
    
    # Cache de dependências do Maven
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    # Instalar Maven e compilar o projeto
    - name: Set up Maven
      uses: cachix/setup-maven@v3
      with:
        maven-version: '3.8.4'  # Use uma versão específica de Maven
    
    - name: Build with Maven
      run: mvn clean install -DskipTests
    
    # Construção da imagem Docker
    - name: Build Docker image
      run: |
        docker build -t deploy_render .

    # Testar se o contêiner Docker está funcionando (opcional)
    - name: Run Docker container
      run: |
        docker run -d -p 8082:8082 deploy_render
        docker ps
    
    # Opcional: Testar a aplicação no Docker
    - name: Check Docker logs
      run: docker logs $(docker ps -q)
